<a href="https://colab.research.google.com/github/sneha2830/CODSOFT/blob/main/credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [6]:
creditcard = pd.read_csv('/content/creditcard.csv')

In [7]:
creditcard.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
creditcard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    13954 non-null  int64
 1   V1      13954 non-null  float64
 2   V2      13954 non-null  float64
 3   V3      13954 non-null  float64
 4   V4      13954 non-null  float64
 5   V5      13954 non-null  float64
 6   V6      13954 non-null  float64
 7   V7      13954 non-null  float64
 8   V8      13954 non-null  float64
 9   V9      13954 non-null  float64
 10  V10     13954 non-null  float64
 11  V11     13954 non-null  float64
 12  V12     13954 non-null  float64
 13  V13     13954 non-null  float64
 14  V14     13954 non-null  float64
 15  V15     13954 non-null  float64
 16  V16     13954 non-null  float64
 17  V17     13954 non-null  float64
 18  V18     13954 non-null  float64
 19  V19     13954 non-null  float64
 20  V20     13954 non-null  float64
 21  V21     13954 non-null  float64
 22  V22     13954 non-null  float64
 23  V23     13954 non-null  float64
 24  V24     13954 non-null  float64
 25  V25     13954 non-null  float64
 26  V26     13954 non-null  float64
 27  V27     13954 non-null  float64
 28  V28     13954 non-null  float64
 29  Amount  13953 non-null  float64
 30  Class   13953 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.3 MB

In [9]:
creditcard.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,...,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13953.000000,13953.000000
mean,10121.161817,-0.235676,0.284287,0.846047,0.302775,-0.118730,0.128013,-0.157297,-0.016148,0.989827,...,-0.068037,-0.157471,-0.035585,0.011158,0.117019,0.035544,0.012787,0.002122,63.882442,0.004013
std,7739.625811,1.720315,1.394804,1.561376,1.500595,1.289494,1.320395,1.238583,1.262024,1.214044,...,0.873942,0.621845,0.499807,0.587225,0.427953,0.558290,0.399550,0.255710,177.887021,0.063227
min,0.000000,-27.670569,-34.607649,-24.667741,-4.657545,-32.092129,-23.496714,-26.548144,-23.632502,-7.175097,...,-11.468435,-8.593642,-19.254328,-2.512377,-4.781606,-1.338556,-7.976100,-3.575312,0.000000,0.000000
25%,2984.250000,-0.969786,-0.282728,0.407297,-0.623141,-0.717155,-0.624025,-0.616307,-0.182270,0.288101,...,-0.271778,-0.549723,-0.173807,-0.339656,-0.135887,-0.374596,-0.076862,-0.014869,5.490000,0.000000
50%,9086.500000,-0.319439,0.252904,0.960978,0.220104,-0.191627,-0.144198,-0.111960,0.016945,0.971414,...,-0.132304,-0.122777,-0.045041,0.060208,0.155162,-0.035825,-0.000950,0.016238,15.690000,0.000000
75%,17103.500000,1.162662,0.884741,1.607031,1.198942,0.351255,0.508494,0.421830,0.265736,1.654184,...,0.018677,0.228997,0.069750,0.392734,0.393032,0.375271,0.098516,0.072497,52.150000,0.000000
max,24759.000000,1.960497,10.558600,4.101716,11.927512,34.099309,21.393069,34.303177,10.535558,10.392889,...,22.614889,4.534454,13.876221,3.200201,5.525093,3.517346,8.254376,4.860769,7712.430000,1.000000

In [11]:
creditcard.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

In [13]:
creditcard['Class'].value_counts()

0.0    13897
1.0       56
Name: Class, dtype: int64

In [16]:
#seperating data for analysis
legit = creditcard[creditcard.Class == 0]
fraud = creditcard[creditcard.Class == 1]

In [17]:
 print(legit.shape)
 print(fraud.shape)

(13897, 31)
(56, 31)

In [19]:
legit.Amount.describe()

count    13897.000000
mean        63.773909
std        177.164503
min          0.000000
25%          5.770000
50%         15.900000
75%         52.370000
max       7712.430000
Name: Amount, dtype: float64

In [20]:
fraud.Amount.describe()

count      56.000000
mean       90.815893
std       310.308450
min         0.000000
25%         1.000000
50%         1.000000
75%         1.025000
max      1809.680000
Name: Amount, dtype: float64

In [24]:
#compare the values for both transactions
creditcard.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10111.481255,-0.217093,0.266252,0.887227,0.276789,-0.107510,0.136745,-0.131462,-0.020385,1.005460,...,0.020758,-0.068686,-0.158230,-0.034834,0.013065,0.117928,0.034349,0.009565,0.002329,63.773909
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

In [25]:
legit_sample = legit.sample(n = 492)

In [28]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [29]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
12258,21413,-9.628191,5.410769,-7.391166,1.663171,-6.087959,-1.938174,-3.599910,5.952054,0.989964,...,0.098244,-0.310455,-0.283372,0.708302,0.011691,-0.441673,0.096153,-0.066120,89.99,0.0
4999,4563,-2.071050,2.153658,0.529213,-0.479327,-0.930649,-0.827955,-0.462825,1.242180,0.723136,...,-0.198593,-0.401251,0.101922,0.512960,-0.087544,0.236889,0.113365,0.101352,1.00,0.0
11960,20651,1.208903,-0.391960,0.903951,-0.698755,-1.001776,-0.278654,-0.818838,0.100279,2.997278,...,-0.136302,0.003578,-0.076918,-0.062133,0.458670,-0.720249,0.055039,0.015380,11.85,0.0
4105,3742,1.462846,-0.582219,-0.879407,-1.642192,1.489665,3.263292,-1.212620,0.718617,0.363858,...,-0.297398,-0.881458,0.109301,0.918388,0.368718,-0.504986,-0.013916,0.009898,10.13,0.0
3220,2793,-0.415072,0.708448,1.220118,-2.107547,0.180918,-1.283255,1.113873,-0.341412,0.473905,...,0.132094,0.751296,-0.290061,0.556844,0.035032,-0.871458,0.239031,-0.020570,1.00,0.0

In [30]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11880,20451,-15.819179,8.775997,-22.804686,11.864868,-9.092361,-2.386893,-16.560368,0.948349,-6.310658,...,-2.350634,1.036362,1.136051,-1.043414,-0.108923,0.657437,2.136424,-1.411945,1.0,1.0
12070,20931,-16.367923,9.223692,-23.270631,11.844777,-9.462037,-2.450444,-16.925152,1.384208,-6.287736,...,-2.343674,1.004602,1.188212,-1.047184,-0.035573,0.664900,2.122796,-1.416741,1.0,1.0
12108,21046,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,-2.336111,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.0,1.0
12261,21419,-17.467710,10.114816,-24.202142,11.805469,-10.198046,-2.579938,-17.656788,2.256902,-6.242149,...,-2.328024,0.940830,1.296817,-1.055104,0.111792,0.679695,2.093541,-1.425491,1.0,1.0
12369,21662,-18.018561,10.558600,-24.667741,11.786180,-10.564657,-2.645681,-18.023468,2.693655,-6.219464,...,-2.319479,0.908839,1.352904,-1.059222,0.185751,0.687037,2.078081,-1.429517,1.0,1.0

In [35]:
new_dataset['Class'].value_counts()

0.0    492
1.0     56
Name: Class, dtype: int64

In [37]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10442.239837,-0.313961,0.265669,0.892435,0.183978,0.040107,0.19045,-0.187917,-0.051210,1.098016,...,-0.036294,-0.005237,-0.175630,-0.026111,0.002408,0.129296,-0.009187,-0.009973,0.012792,52.545976
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.03036,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

In [38]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [39]:
print(X)

        Time         V1         V2         V3         V4         V5        V6  \
12258  21413  -9.628191   5.410769  -7.391166   1.663171  -6.087959 -1.938174
4999    4563  -2.071050   2.153658   0.529213  -0.479327  -0.930649 -0.827955
11960  20651   1.208903  -0.391960   0.903951  -0.698755  -1.001776 -0.278654
4105    3742   1.462846  -0.582219  -0.879407  -1.642192   1.489665  3.263292
3220    2793  -0.415072   0.708448   1.220118  -2.107547   0.180918 -1.283255
...      ...        ...        ...        ...        ...        ...       ...
11880  20451 -15.819179   8.775997 -22.804686  11.864868  -9.092361 -2.386893
12070  20931 -16.367923   9.223692 -23.270631  11.844777  -9.462037 -2.450444
12108  21046 -16.917468   9.669900 -23.736443  11.824990  -9.830548 -2.514829
12261  21419 -17.467710  10.114816 -24.202142  11.805469 -10.198046 -2.579938
12369  21662 -18.018561  10.558600 -24.667741  11.786180 -10.564657 -2.645681

              V7        V8        V9  ...       V20       V21       V22  \
12258  -3.599910  5.952054  0.989964  ... -0.019437  0.098244 -0.310455
4999   -0.462825  1.242180  0.723136  ... -0.027309 -0.198593 -0.401251
11960  -0.818838  0.100279  2.997278  ... -0.179627 -0.136302  0.003578
4105   -1.212620  0.718617  0.363858  ...  0.157231 -0.297398 -0.881458
3220    1.113873 -0.341412  0.473905  ...  0.070963  0.132094  0.751296
...          ...       ...       ...  ...       ...       ...       ...
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362
12070 -16.925152  1.384208 -6.287736  ...  0.993585 -2.343674  1.004602
12108 -17.290657  1.820408 -6.264903  ...  0.996745 -2.336111  0.972755
12261 -17.656788  2.256902 -6.242149  ...  1.001519 -2.328024  0.940830
12369 -18.023468  2.693655 -6.219464  ...  1.007703 -2.319479  0.908839

            V23       V24       V25       V26       V27       V28  Amount
12258 -0.283372  0.708302  0.011691 -0.441673  0.096153 -0.066120   89.99
4999   0.101922  0.512960 -0.087544  0.236889  0.113365  0.101352    1.00
11960 -0.076918 -0.062133  0.458670 -0.720249  0.055039  0.015380   11.85
4105   0.109301  0.918388  0.368718 -0.504986 -0.013916  0.009898   10.13
3220  -0.290061  0.556844  0.035032 -0.871458  0.239031 -0.020570    1.00
...         ...       ...       ...       ...       ...       ...     ...
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00
12070  1.188212 -1.047184 -0.035573  0.664900  2.122796 -1.416741    1.00
12108  1.241866 -1.051086  0.038009  0.672317  2.108471 -1.421243    1.00
12261  1.296817 -1.055104  0.111792  0.679695  2.093541 -1.425491    1.00
12369  1.352904 -1.059222  0.185751  0.687037  2.078081 -1.429517    1.00

[548 rows x 30 columns]

In [41]:
print(Y)

12258    0.0
4999     0.0
11960    0.0
4105     0.0
3220     0.0
        ...
11880    1.0
12070    1.0
12108    1.0
12261    1.0
12369    1.0
Name: Class, Length: 548, dtype: float64

In [43]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [44]:
print(X.shape, X_train.shape, X_test.shape)

(548, 30) (438, 30) (110, 30)

# model training

# Logistic Regression

In [45]:
model= LogisticRegression()

In [47]:
#training the Logistic Regression model with training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# model evaluation

# accuracy score

In [48]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [49]:
print('Accuracy on Training data:', training_data_accuracy)

Accuracy on Training data: 0.9885844748858448

In [50]:
#accuracy on test
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [51]:
print('Accuracy score on Test data:', training_data_accuracy)

Accuracy score on Test data: 0.9885844748858448